// <auto-generated>
//------------------------------------------------------------------------------
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public class CompraViagem
    {
        public CompraViagem()
        {

        }
    
        public int Id { get; set; }
        public string NomeCliente { get; set; }
        public int Parcelamento { get; set; }
        public int NumeroCartao { get; set; }
        public int CodCartao { get; set; }
        public int IdVigem { get; set; }

        public CompraViagem[] RetornaComprasViagens()
        {
            var compraViagens = new CompraViagem[]
            {

            };
            return compraViagens;
        }


        
    }
}
