//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Hospedagem
    {
        public int Id { get; set; }
        public int IdLocal { get; set; }
        public int QuartosDisponiveis { get; set; }

        public Hospedagem[] RetornaHospedagens()
        {
            var hospedagens = new Hospedagem[]
            {
                new Hospedagem { Id = 01 , IdLocal = 04 , QuartosDisponiveis = 30},
                new Hospedagem { Id = 02 , IdLocal = 05 , QuartosDisponiveis = 22},
                new Hospedagem { Id = 03 , IdLocal = 06 , QuartosDisponiveis = 9}
            };
            return hospedagens;
        }
    }
}
