//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Local
    {    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }

        public Local[] RetornaLocais()
        {
            var locais = new Local[]
            {
                new Local { Id = 01, Nome = "Afonso Pena", Cidade = "Curitiba", Estado = "PR", Pais = "BR"},
                new Local { Id = 02, Nome = "Congonhas", Cidade = "São Paulo", Estado = "SP", Pais = "BR"},
                new Local { Id = 03, Nome = "Galeão", Cidade = "Rio de Janeiro", Estado = "RJ", Pais = "BR"},
                new Local { Id = 04, Nome = "Hotel Anna", Cidade = "Curitiba", Estado = "PR", Pais = "BR"},
                new Local { Id = 05, Nome = "Hotel Jessica", Cidade = "São Paulo", Estado = "SP", Pais = "BR"},
                new Local { Id = 06, Nome = "Hotel Maristel", Cidade = "Rio de Janeiro", Estado = "RJ", Pais = "BR"}

            };
            
            return locais;
        }

        public void MudaNome(String nome)
        {
            Nome = nome;
        }
    }
}
