//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public class TicketHospedagem
    {

        public int Id { get; set; }
        public string Nome { get; set; }
        public int IdCompraHospedagem { get; set; }
    }
}
