//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Viagem
    {
        public int Id { get; set; }
        public int IdLocalOrigem { get; set; }
        public int IdLocalDestino { get; set; }
        public DateTime DataViagem { get; set; }
        public int QtdDisponivel { get; set; }

        internal Viagem[] RetornaViagens()
        {
            var viagens = new Viagem[]
            {
                new Viagem { Id = 01 , IdLocalOrigem = 01 , IdLocalDestino = 03 , DataViagem = new DateTime(2018,06,20,22,15,00) , QtdDisponivel = 100},
                new Viagem { Id = 02 , IdLocalOrigem = 02 , IdLocalDestino = 01 , DataViagem = new DateTime(2018,07,22,08,15,00) , QtdDisponivel = 90},
                new Viagem { Id = 03 , IdLocalOrigem = 03 , IdLocalDestino = 02 , DataViagem = new DateTime(2018,08,17,21,40,00) , QtdDisponivel = 105}
            };
            return viagens;
        }

    }
}
